FROM pytorch/pytorch:1.9.0-cuda10.2-cudnn7-runtime
RUN apt update && apt install build-essential ffmpeg libsm6 libxext6 git -y

RUN apt-get update && apt-get install -y \
  ffmpeg \
  libgl1-mesa-dev \
  python3-pip \
  unrar \
  wget \
  && apt-get clean

ADD requirements.txt /tmp/
RUN pip install --no-cache-dir -r /tmp/requirements.txt
